version: "3.1"
#---------------------------postgres---------------
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - product-ms:/var/lib/postgresql/data
    networks:
      - product-ms

  card-ms:
    hostname: product-ms
    image: product-ms
    ports:
      - "8080:8080"
    environment:
      DB: db
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    depends_on:
      - db
    networks:
      - product-ms

volumes:
  product-ms:

networks:
  product-ms: