spring:
  application:
    name: docker-task
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB:127.0.0.1}:5432/postgres
    password: ${DB_PASSWORD:123456}
    username: ${DB_USERNAME:postgres}
server:
  port: 8081
  servlet:
    context-path: /customer-ms