version: "3.1"
#---------------------------postgres---------------
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - docker-task-volume:/var/lib/postgresql/data
    networks:
      - docker-task-net

#-----------------------adminer--------------------
  adminer:
    image: adminer
    ports:
      - "8089:8080"
    networks:
      - docker-task-net
    depends_on:
      - db
  #-------------------------app----------------------
  customer-ms:
    image: customer-ms
    hostname: customer-ms
    ports:
      - "8081:8081"
    environment:
      DB: db
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    depends_on:
      - db
    networks:
      - docker-task-net

  card-ms:
    hostname: card-ms
    image: card-ms
    ports:
      - "8082:8081"
    environment:
      DB: db
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    depends_on:
      - db
    networks:
      - docker-task-net

  reverse_proxy:
    image: nginx
    hostname: proxy
    container_name: reverse_proxy
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - docker-task-net
    depends_on:
      - card-ms
      - customer-ms

volumes:
  docker-task-volume:

networks:
  docker-task-net: