version: "3.1"
#---------------------------postgres---------------
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - docker-task-volume:/var/lib/postgresql/data
    networks:
      - docker-task-net

#-----------------------adminer--------------------
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - docker-task-net
    depends_on:
      - db
  #-------------------------app----------------------
  docker-task:
    image: docker-task
    ports:
      - "8081:8081"
    environment:
      DB: db
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    depends_on:
      - db
    networks:
      - docker-task-net


volumes:
  docker-task-volume:

networks:
  docker-task-net: