spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      properties:
          spring:
            json:
              trusted-packages: com.example.kafka
