spring:
  profiles:
    include:
      - db
      - common
      - twilio
    active: ${ACTIVE-PROFILE:dev}
logging:
  level:
    web: debug


#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      custom-appender-class: com.company.classworkrelationhomework.util.CustomSQLFormat
#      logging: custom


